services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 #--reload so that changes in python files need not be done using docker down
    volumes:
      - ./backend/src:/app
    develop:
      watch: # same can be done with any files
        - action: rebuild
          path: backend/require.txt
        - action: restart
          path: backend/src/


  app:
    build:
      context: .
      dockerfile: static.dockerfile
    ports:
      - "8000:8000"
    command: python -m http.server 8000
    volumes:
      - ./src:/app